alias hm="helm"
alias hml="helm list"
alias hmi="helm install"
alias hmu="helm upgrade"
alias hms="helm search repo"
export HELM_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}/helm"
export HELM_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/helm"
export HELM_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}/helm"
